### ISSUE TITLE
Config file from another directory is not resolved

### ISSUE THREAD

**Issue by alex-ber** [alex-ber/AlexBerUtils#8]
I have my configuration file in _conf_ directory.
I am expecting this code to work, but I'm getting HiYaPyCoInvocationException.

```python
from argparse import ArgumentParser
import alexber.utils.init_app_conf as init_app_conf

argumentParser = ArgumentParser(conflict_handler='resolve')
argumentParser.add_argument("--general.config.file", nargs='?', dest='config_file', default='conf/config.yml',
                            const='conf/config.yml')

dd = init_app_conf.parse_config(argumentParser=argumentParser, args=args)
```

This is the output:

```python
ERROR MainProcess [hiyapyco.__init__] file not found: config.yml (C:\dev\work\example\config.yml)
Traceback (most recent call last):
  File "C:\dev\work\example\venv\lib\site-packages\hiyapyco\__init__.py", line 198, in __init__
    with io.open(fn, 'r', encoding=self.encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\dev\\work\\example\\config.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\work\example\runner.py", line 14, in run
    _run(args=args)
  File "C:\dev\work\example\app.py", line 44, in _run
    dd = init_app_conf.parse_config(argumentParser=argumentParser, args=args)
  File "C:\dev\work\example\venv\lib\site-packages\alexber\utils\init_app_conf.py", line 455, in parse_config
    dd = parser.parse_config(argumentParser=argumentParser, args=args)
  File "C:\dev\work\example\venv\lib\site-packages\alexber\utils\init_app_conf.py", line 260, in parse_config
    sys_d, profiles, white_list, list_ensure, config_file = self._parse_sys_args(argumentParser=argumentParser,
  File "C:\dev\work\example\venv\lib\site-packages\alexber\utils\init_app_conf.py", line 244, in _parse_sys_args
    default_d = ymlparsers.load([str(full_path)])
  File "C:\dev\work\example\venv\lib\site-packages\alexber\utils\ymlparsers.py", line 157, in load
    hiyapyco = HiYaPyCo(*args, **kwargs)
  File "C:\dev\work\example\venv\lib\site-packages\hiyapyco\__init__.py", line 210, in __init__
    raise HiYaPyCoInvocationException(
hiyapyco.HiYaPyCoInvocationException: yaml file not found: 'config.yml'

Process finished with exit code 1
```

**Comment by alex-ber** [comment]
Actually, this is intended behavior.

_argumentParser_ lacks API for checking if _'--general.config.file'_ is already defined. I don't want to rely on protected attributes/methods. 

I don't want to mandate to specify _'--general.config.file'_ if you're specifying some parameter through _argumentParser_. 

Proposed work-around:

```python
from pathlib import Path
full_path = Path('conf/config.yml').resolve()  # relative to cwd
args = {*args, f'--general.config.file={full_path}'}
dd = init_app_conf.parse_config(args=args)

```
